/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class EditarCurso extends javax.swing.JDialog {
    
    private CursoIController cursoController; //relação com o controller
    private Long cursoIdAtual; //variavel para guardar o id do curso em edição
    /**
     * Creates new form EditarCurso
     */
    
    //Novo construtor para abrir a tela de edição com um curso especifico
    public EditarCurso(java.awt.Frame parent, boolean modal, CursoIController controller) {
        super(parent, modal);
        initComponents();
        this.cursoController = controller; // Instancia o Controller
        this.cursoIdAtual = null; // Guarda o ID do curso que será editado
        setLocationRelativeTo(parent);

        // Carregar os dados do curso nos campos da tela se um ID foi fornecido
        if (this.cursoIdAtual != null) {
            carregarDadosCursoParaEdicao(this.cursoIdAtual); // Chama o método para preencher os campos
        }
    }
    
    public EditarCurso(java.awt.Frame parent, boolean modal, Long idCurso, CursoIController controller) { 
        super(parent, modal);
        initComponents();
        // AQUI: A View recebe o Controller da tela pai
        this.cursoController = controller;
        this.cursoIdAtual = idCurso; // Guarda o ID do curso que será editado
        setLocationRelativeTo(parent);

        // Carregar os dados do curso nos campos da tela se um ID foi fornecido
        if (this.cursoIdAtual != null) {
            carregarDadosCursoParaEdicao(this.cursoIdAtual); // Chama o método para preencher os campos
        } else {
            // Se o ID for nulo (caso use este construtor para adição), ajuste o título e o botão
            jLabel1.setText("ADICIONAR NOVO CURSO");
            btnAdicionar.setText("Adicionar");
            // Limpe os campos se for para adicionar (caso não sejam limpos por padrão)
            txtNome.setText("");
            txtCodigo.setText("");
            boxEstado.setSelectedItem("ATIVO"); // Default para novo curso
        }
    }
    
    private void carregarDadosCursoParaEdicao(Long id) {
    try {
        // Usa o Controller para buscar o curso pelo ID
        Curso curso = cursoController.findById(id);
        if (curso != null) {
            // Preenche os campos da tela com os dados do curso
            txtNome.setText(curso.getNome());
            txtCodigo.setText(curso.getCodigoCurso());

            // Preenche o JComboBox 'boxEstado' com base no status 'ativo'
            if (curso.isAtivo()) {
                boxEstado.setSelectedItem("ATIVO");
            } else {
                boxEstado.setSelectedItem("INATIVO");
            }
        } else {
            // Se o curso não for encontrado, avisa e fecha.
            JOptionPane.showMessageDialog(this, "Curso não encontrado para edição (ID: " + id + ").", "Erro", JOptionPane.ERROR_MESSAGE);
            this.dispose(); // Fecha a tela
        }
    } catch (RuntimeException ex) {
        
        JOptionPane.showMessageDialog(this, "Erro ao carregar dados do curso para edição: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
        this.dispose(); // Fecha a tela em caso de erro
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        boxEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("EDITAR CURSO");

        btnAdicionar.setText("Salvar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNome.setText("jTextField1");

        lblNome.setText("Nome");

        lblCodigo.setText("Codigo");

        txtCodigo.setText("jTextField1");

        lblEstado.setText("Etado");

        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(boxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAdicionar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // 1. Coletar os dados dos campos da tela
    String nome = txtNome.getText();
    String codigo = txtCodigo.getText();
    // Pega o status do JComboBox
    boolean ativo = boxEstado.getSelectedItem().equals("ATIVO");

    // 2. Validação básica de campos vazios (o Service fará validações mais robustas)
    if (nome.isEmpty() || codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nome e Código do Curso são obrigatórios.", "Validação", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // 3. Criar uma instância da entidade Curso com os novos dados
        Curso cursoParaOperacao = new Curso(); // Certifique-se de ter um construtor vazio em Curso
        cursoParaOperacao.setNome(nome);
        cursoParaOperacao.setCodigoCurso(codigo);
        cursoParaOperacao.setAtivo(ativo);

        // 4. Lógica de SAVE ou UPDATE com base em 'cursoIdAtual'
        if (cursoIdAtual == null) { // Se cursoIdAtual é nulo, é um NOVO cadastro
            cursoController.save(cursoParaOperacao); // Chama o save do Controller
            JOptionPane.showMessageDialog(this, "Curso salvo com sucesso!");
        } else { // Se cursoIdAtual não é nulo, é uma ATUALIZAÇÃO
            cursoParaOperacao.setId(cursoIdAtual); // Define o ID no objeto para atualização
            cursoController.update(cursoParaOperacao); // Chama o update do Controller
            JOptionPane.showMessageDialog(this, "Curso atualizado com sucesso!");
        }

        this.dispose(); // Fecha a janela após a operação ser concluída com sucesso

    } catch (RuntimeException ex) {
        // Captura qualquer RuntimeException (ou subclasse) que o Controller relance.
        JOptionPane.showMessageDialog(this, "Erro na operação: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace(); // Imprime o stack trace completo para depuração
    }
        
        
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        JOptionPane.showMessageDialog(this, "Edição realizada com sucesso.");
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
