/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import br.com.ifba.curso.view.renderer.Redenrizador;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class CursoListar extends javax.swing.JFrame {
    
    private DefaultTableModel modeloTabelaProdutos;
    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        
        //Configuração do modelo de tabela
        //Definindo o nome das colunas
        String[] nomeColunas = {"ID","Curso","Cod.","Ativo","Remover","Editar"};
        //INstanciando um objeto da classe DefaulltTableModel que declaramos la em cima
        //passo os nomes das colunas e defino que começa com zero linhas
        modeloTabelaProdutos = new DefaultTableModel(nomeColunas,5);
        
        //Agora aqui eu indico que minha tabela de produtos vai seguir o modelo definido 
        tblCursos.setModel(modeloTabelaProdutos); 
        
        
        // Crie os objetos ImageIcon para suas imagens
        // Caminho para as imagens: "/images/nome_da_sua_imagem.png"
        // As imagens devem estar em src/main/resources/images
        ImageIcon iconeLixeira = new ImageIcon(getClass().getResource("/images/icons8-lixeira-25.png"));
        ImageIcon iconeLapis = new ImageIcon(getClass().getResource("/images/icons8-editar-25.png"));

        // Aplique o ButtonRenderer às colunas "Remover" e "Editar"
        // (Assumindo que "Remover" é a coluna de índice 4 e "Editar" é a de índice 5)
        tblCursos.getColumn("Remover").setCellRenderer(new Redenrizador(iconeLixeira));
        tblCursos.getColumn("Editar").setCellRenderer(new Redenrizador(iconeLapis));

        // Opcional: Aumente a altura da linha para o ícone caber melhor
        tblCursos.setRowHeight(30);
        
        tblCursos.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            int column = tblCursos.columnAtPoint(e.getPoint());
            int row = tblCursos.rowAtPoint(e.getPoint());

            if (row >= 0 && column >= 0) {
                // Para o teste visual, podemos usar a linha para identificar o item.
                // Long cursoId = (Long) jTableCursos.getModel().getValueAt(row, 0); // Para pegar o ID do BD

                String clickedColumnName = tblCursos.getColumnName(column);

                if (clickedColumnName.equals("Remover")) {
                    System.out.println("Ícone REMOVER clicado na linha: " + row);
                    int confirm = JOptionPane.showConfirmDialog(CursoListar.this,
                            "Tem certeza que deseja excluir o item da linha " + (row + 1) + "?",
                            "Confirmar Exclusão",
                            JOptionPane.YES_NO_OPTION);

                    if (confirm == JOptionPane.YES_OPTION) {
                        JOptionPane.showMessageDialog(rootPane, "Iten excluido com sucesso");
                        System.out.println("Usuário confirmou exclusão da linha: " + (row + 1));
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Exclusão cancelada");
                        System.out.println("Usuário CANCELOU exclusão da linha: " + (row + 1));
                    }
                } else if (clickedColumnName.equals("Editar")) {
                    System.out.println("Ícone EDITAR clicado na linha: " + row);
                    // CHAME O MÉTODO PARA ABRIR A TELA EditarCurso AQUI
                    abrirTelaEdicao(row); //abro a tela de edição passando o numero da linha
                }
            }
        }
    });
            
    }
    
    private void abrirTelaEdicao(int row) { // Agora o método recebe a linha clicada
        System.out.println("Chamando tela de edição para a linha: " + (row + 1));
        // Instancia a sua JDialog EditarCurso
        // 'this' refere-se à instância atual de CursoListar (o JFrame pai)
        // 'true' torna o diálogo modal (bloqueia a tela pai até ser fechado)
        EditarCurso telaEdicao = new EditarCurso(this, true);

        // Opcional: Centralizar o diálogo em relação à tela pai
        telaEdicao.setLocationRelativeTo(this);

        // Torna o diálogo visível
        telaEdicao.setVisible(true);

        // Esta linha só será executada DEPOIS que a telaEdicao for fechada
        System.out.println("Tela de Edição (EditarCurso) foi fechada.");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textProcurar = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textProcurar.setText("Procurar...");

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-adicionar-25.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(textProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        //Crio uma instancia da nova tela criada para exibi-la
        AdicionarCurso telaAdicao = new AdicionarCurso(this, true);
        
        //dessa forma uso a posição relativa da janela em questão e abro a segunda em relação a ela
        telaAdicao.setLocationRelativeTo(this);
        //comando para tornar a janela visivel
        telaAdicao.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField textProcurar;
    // End of variables declaration//GEN-END:variables
}
